# Generated by Django 3.1.3 on 2021-01-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('January', '0002_bod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('photo_url', models.TextField()),
            ],
        ),
    ]
